
[theme]
#base="light"
primaryColor="#004F45"
backgroundColor="#fff"
secondaryBackgroundColor="#97B1AB"
textColor="#000"
#[theme]
#primaryColor = "#f63366"
# backgroundColor = "#10344b"
#backgroundColor = "#111111"
# secondaryBackgroundColor = "#154360"
#secondaryBackgroundColor = "#393939"

#font = "sans serif"
#[theme]
#base="dark"
#primaryColor="#19f960"
#font="sans serif"
#[theme]
#base="light"
#primaryColor="#004F45"
#backgroundColor="#fff"
#backgroundColor="#12250d"
#secondaryBackgroundColor="#2d312c"
#secondaryBackgroundColor="#DEDDC2"

[server]
enableStaticServing = true
#[theme]

#primaryColor="#59914f"
#secondaryBackgroundColor="#b7a51d"
#font="serif"

