#[theme]
#primaryColor = "#f63366"
# backgroundColor = "#10344b"
#backgroundColor = "#111111"
# secondaryBackgroundColor = "#154360"
#secondaryBackgroundColor = "#393939"

#font = "sans serif"
#[theme]
#base="dark"
#primaryColor="#19f960"
#font="sans serif"
[theme]
base="light"
primaryColor="#4D5A3A"
backgroundColor="#fff"
#backgroundColor="#12250d"
#secondaryBackgroundColor="#2d312c"
secondaryBackgroundColor="#95B393"
textColor = "#0A0C0A"
[server]
enableStaticServing = true
#[theme]
#base="light"
#primaryColor="#59914f"
#secondaryBackgroundColor="#f2efe3"
#font="serif"

